[package]
name = "iroha_macro_utils"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
syn = { workspace = true, features = ["default", "parsing", "printing"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-error = { workspace = true }
